// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tenant.Context;

namespace Tenant.Migrations
{
    [DbContext(typeof(MultiTenantContext))]
    [Migration("20210317235141_database-data")]
    partial class databasedata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Entities.TenantModels.Multitenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Attribute1")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Attribute2")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Attribute3")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Attribute4")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Attribute5")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenantConnectionString")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("TenantUrl")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TenantId");

                    b.ToTable("Multitenants");
                });
#pragma warning restore 612, 618
        }
    }
}
